apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replace-url
replacements:
  - source:
      value: "base-*.nigam.cloud"
      replacement: "prod-*.nigam.cloud"
    targets:
      - select: {}  # matches all objects
        # List explicit field paths where the replacement should occur:
        # fieldPaths:
        #   - spec.url
        #   - metadata.name  # example additional field; add more as needed
