apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
#   - ../base/platform

commonLabels:
  platform-environment: production

namespace: platform-production

patches:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: platform
    patch: |-
      - op: replace
        path: /metadata/name
        value: platform-production

# transformers:
#   - patches/replace-url.yaml